INSERT INTO person(name,lastname,position,company,program,address1,created_at,is_active_access) VALUES

("Jorge Alberto", "Coello Elvir","Coordinador de Revistazo",12,32,"Tegucigalpa",NOW(),0),
("Hilda ", "Núñez Velásquez","Servicios Generales",3,0,"Tegucigalpa",NOW(),0),
("Francisco ",	"Betanco","Conserje",3,	33,"Tegucigalpa",NOW(),0),
("Deisy Leticia", "Ordóñez Aguilar","Oficial Contable",3,7,"Tegucigalpa",NOW(),0),
("Sandra del Milagro", "Palma Mejía","Promotora Social",5,9,"Tegucigalpa",NOW(),0),
("Blanca Lidia", "Munguía Rodríguez","Directora Social ",5,17,"Tegucigalpa",NOW(),0),
("Audrey Jackeline", "Arguijo Lara","Recepcionista",3,0,"Tegucigalpa",NOW(),0),
("Carlos Gilberto", "Gómez Pérez","Director de Operaciones",3,14,"Tegucigalpa",NOW(),0),
("Keila Eunice", "García Ventura",	"Directora de Gestion Publica",7,20,"Tegucigalpa",NOW(),0),
("Vicky Esmeralda", "Baca Laínez",	"Oficial Contable	",3,7,"Tegucigalpa",NOW(),0),
("Jorge Adiel", "Zelaya Mejía",	"Contador General",3,7,"Tegucigalpa",NOW(),0),
("Oscar David", "Castillo Ordóñez",	"Oficial Analista de Datos",4,21,"Tegucigalpa",NOW(),0),
("Joel Andrés", "González González","Técnico en Investigación",10,30,"Tegucigalpa",NOW(),0),
("Jessika ", "Guzmán González",	"Oficial de Programas",3,14,"Tegucigalpa",NOW(),0),
("Jaime Geovanni", "Varela Lagos",	"Coordinador de Paz y Justicia",10,	25	,"Tegucigalpa",NOW(),0),
("Maribel Muñoz", "Aguilar",	"Directora de Programas	",13,	15 	,"Tegucigalpa",NOW(),0),
("Edis Alexis", "Morales Ávila",	"Técnico en Investigación	",10,	25	,"SanPedroSula",NOW(),0),
("Carlos Hernán", "García Mejía",	"Oficial de Redes	",3,	22	,"Tegucigalpa",NOW(),0),
("Anajansi ", "Alvarado Cruz",	"Oficial de Programas ",1, 	17	,"Tegucigalpa",NOW(),0),
("Mario Alejandro", "Romero Cruz",	"Auditor Social	",1,1,"Tegucigalpa",NOW(),0),
("Jessica Johanna", "Pavón Osorto",	"Sub Coordinadora "	,9,	6	,"Tegucigalpa",NOW(),0),
("María Bernarda", "García Rodríguez",	"Oficial en Psicología	",10,	25	,"Tegucigalpa",NOW(),0),
("Wendoly Leticia", "Castillo Martínez",	"Oficial en Psicología	",10,	25	,"Tegucigalpa",NOW(),0),
("Oscar Yovany", "Rodríguez Contreras",	"Oficial de Finanzas",14,	15 	,"Tegucigalpa",NOW(),0),
("Merlin Ursina", "Amaya Gómez",	"Oficial de Bienes y Sumistros",3,	0	,"Tegucigalpa",NOW(),0),
("Gladys Yosmary", "García Sierra",	"Auditor Social Junior",7,	20	,"Tegucigalpa",NOW(),0),
("Claudia Alexandra", "Gómez Ruíz",	"Oficial de Comunicaciones",9,6,"Tegucigalpa",NOW(),0),
("Emilio de", "Jesús Lara Parada","Guardaespalda",3,33,"Tegucigalpa",NOW(),0),
("Dineyla Leticia", "Erazo Arias",	"Asistente Administrativo de Dirección",13,	10	,"Tegucigalpa",NOW(),0),
("Argedia Ninoska", "Reyes Cálix",	"Coordinadora de APJ	",10,	3	,"Tegucigalpa",NOW(),0),
("Alin Anilegna", "Granados Ramírez",	"Oficial en Psicología	",10,	25	,"SanPedroSula",NOW(),0),
("Marco ", "Antonio Sánchez",	"Oficial Legal	",10,	25	,"Tegucigalpa",NOW(),0),
("Dolores Jesús", "Martínez Guevara",	"Coordinadora de Laboratorio de Impacto Juvenil 	",11,	9	,"Tegucigalpa",NOW(),0),
("María Estela", "Núñez Rivera",	"Facilitadora	",11,	9	,"Tegucigalpa",NOW(),0),
("Oswaldo Martín", "Rojas Flores",	"Motorista	",3,	0	,"Tegucigalpa",NOW(),0),
("Sandra Maribel", "Vásquez Vásquez",	"Servicios Generales	",3,	0	,"Tegucigalpa",NOW(),0),
("Russlan Yupanky", "Espinal Sánchez",	"Oficial de DDHH	",10,	3	,"Tegucigalpa",NOW(),0),
("Sonia Beatriz", "Solano Rodríguez",	"Promotora Social	",11,	9	,"Tegucigalpa",NOW(),0),
("Katheryn Gissel", "Soto Muñoz",	"Oficial de Desarrollo	",3,	0	,"Tegucigalpa",NOW(),0),
("Mario José", "Quiroz López",	"Motorista",3,	33	,"Tegucigalpa",NOW(),0),
("Ivyng Ruth", "Arias Ventura",	"Oficial Contable",3,	7	,"Tegucigalpa",NOW(),0),
("Ismary Patricia", "Irías Padilla",	"Auditor Social Senior ",7,	20	,"Tegucigalpa",NOW(),0),
("Alejandra Eunice", "Vargas Mejía",	"Oficial de auditoria social	",10,	3	,"Tegucigalpa",NOW(),0),
("Luis Orlando", "Adriano Cabrera",	"Oficial de Servicios Generales 	",3,	0	,"Tegucigalpa",NOW(),0),
("Yury Lizzeth", "Gómez Salinas",	"Oficial de RRHH	",3,	29 	,"Tegucigalpa",NOW(),0),
("Howard ", "Guzmán González", 	"Analista Sectorial	",7,	20	,"Tegucigalpa",NOW(),0),
("Kirstin ", "Lee Garrison",	"Oficial de Investigaciones y Comunicaciones",12,	32	,"Tegucigalpa",NOW(),0),
("Jordy Alexander", "Palencia Bustamante",	"Desarrollador de Sistemas	",3,	22	,"Tegucigalpa",NOW(),0),
("Edwin Daniel", "Flores Flores",	"Asistente Administrativo",3,	0 	,"Tegucigalpa",NOW(),0),
("Glenda Yojana", "Díaz Flores",	"Oficial Contable",3,	7	,"Tegucigalpa",NOW(),0),
("Evelyn Karolina", "Moreno Quiroz",	"Oficial de Transformemos Honduras",1, 	39	,"Tegucigalpa",NOW(),0),
("Francis Leticia", "Martínez Martínez",	"Oficial de Finanzas",14,	15	,"Tegucigalpa",NOW(),0),
("Lizeth del Carmen", " Hernández Leiva",	"Oficial de Viajes",3,	0	,"Tegucigalpa",NOW(),0),
("Laura Iveth", "Marcia Martínez",	"Sub Coordinadora",10,	30	,"SanPedroSula",NOW(),0),
("Mariela Lituania", "Aguilar Rodríguez",	"Especialista Técnico Legal	",10,	40	,"Tegucigalpa",NOW(),0),
("Elmer Josué", "Salinas Matute",	"Promotor Social	",5,	9	,"Tegucigalpa",NOW(),0),
("Estefany Gabriela", "Varela Chandias",	"Promotora Social	",5,1,"Tegucigalpa",NOW(),0),
("Karen Sofía", "Mendoza Muñoz","Administradora AJS	",3,1,"Tegucigalpa",NOW(),0),
("Karen Magdalena", "Mejía Medrano","Especialista de 28	",4,	28	,"Tegucigalpa",NOW(),0),
("Cristhian Iván", "Espinoza Ortíz", 	"Técnico en 22	",3,	22	,"Tegucigalpa",NOW(),0),
("Walter Mauricio", "Castellanos Laínez",	"Técnico en Investigación	",10,	25	,"Tegucigalpa",NOW(),0),
("Carlos Alberto", "Hernández Martínez",	"Director Ejecutivo	",13,	10	,"Tegucigalpa",NOW(),0),
("Mittchel Alexandra", "Benitez Torres",	"Oficial de Programas 	",2	,2,	"Tegucigalpa",NOW(),0),
("Rafael ", "Jerez Moreno",	"Asistente Jurídico 	",8,	12 	,"Tegucigalpa",NOW(),0),
("Carlos Fernando", "Villatoro","Oficial Cristianos Valientes",6,8,"Tegucigalpa",NOW(),0),
("Gerardo Ernesto", "Sanchez Perdomo","Especialista en Investigación	",12,	2	,"Tegucigalpa",NOW(),0),
("José Antonio", "Herrera Matute", 	"Oficial Técnico en 29 	",7,	20	,"Tegucigalpa",NOW(),0),
("Liliam Raquel", "Romero Núñez",	"Especialista en Gestión por Resultados	",7,	20	,"Tegucigalpa",NOW(),0),
("Luis Nahun", "Rivera Valladares",	"Oficial de PME"	,4, 	28	,"Tegucigalpa",NOW(),0),
("Doris Alejandra", "Reyes Cruz,",	"Auxiliar de Recursos Humanos	",3,	29 	,"Tegucigalpa",NOW(),0),
("Claudia Gisselle", "Elvir Martínez",	"Oficial de Programas 	",10,10	,"Tegucigalpa",NOW(),0),
("Ana María", "Flores Larios",	"Oficial de PME"	,4, 	28	,"Tegucigalpa",NOW(),0),
("Vicente Fernando", "Gonzalez García",	"Oficial de Juventud",2,2	,"Tegucigalpa",NOW(),0),
("Cecilia Sarai", "Salcedo Tabora",	"Asistente de Compras"	,3,	0	,"Tegucigalpa",NOW(),0),
("José Orlando", "Pavón Osorto",	"Especialista Legal	",12,	2	,"Tegucigalpa",NOW(),0),
("Lester José",  "Ramírez Irías",	"Director de Transparencia 	",12	,12	,"Tegucigalpa",NOW(),0),
("Kenneth Rolando", "Madrid Chinchilla",	"Director de 33 y Justicia 	",10,10	,"Tegucigalpa",NOW(),0),
("José Edwin", "Moya Palma", 	"Director de Educación 	",1,1,"Tegucigalpa",NOW(),0),
("Kurt Alan", "Ver Beek",	"Presidente	",13,	10	,"Tegucigalpa",NOW(),0),
("Lesly Yolany", "García Ramirez",	"Servicios Generales"	,3,	0	,"Tegucigalpa",NOW(),0),
("Alejandro Arturo", "Venegas Padilla",	"Motorista/mensajero	",3,	0	,"Tegucigalpa",NOW(),0),
("Silvia Lorena", "Díaz Bustillo",	"Auxiliar Contable"	,3,	7	,"Tegucigalpa",NOW(),0),
("Iving Yojana", "Galindo	Asistente", "Administrativa"	,3,	1	,"Tegucigalpa",NOW(),0),
("Dora Eleticia", "Arias López",	"Auxiliar Contable	",3,	7	,"Tegucigalpa",NOW(),0),
("Comfort ","Sampong","Oficial de Comunicaciones",9,	1	,"Tegucigalpa",NOW(),0),
("Cesiah Raquel", "Jiménez Guevara",	"Asistente Administrativo",10,	40	,"Tegucigalpa",NOW(),0),
("Ingrid Johana", "Ponce Hernandez",	"Auxiliar de Recursos Humanos"	,3,	29	,"Tegucigalpa",NOW(),0),
("Carlos Alberto", "Martínez",	"Of. Jr de Relaciones Públicas y comunicaciones	",2,	6	,"Tegucigalpa",NOW(),0),
("Claudia Michell", "Mairena ",NULL,10,	40	,"Tegucigalpa",NOW(),0),
("Alejandra María", "González",NULL,10,	40	,"Tegucigalpa",NOW(),0),
("Analy ","González",NULL,10,40,"Tegucigalpa",NOW(),0),
("Andreas Ravnsborg", "Daugaard",NULL,7,7,"Tegucigalpa",NOW(),0),
("Luis Alberto", "Luna Aranda",	"Oficial Regional San Pedro Sula",2,8,"SanPedroSula",NOW(),0),
("Carlos Enrique", "Espinal",NULL,7,7,"Tegucigalpa",NOW(),0),
("Daniel Emilio", "Rodríguez ",NULL,7,7,"Tegucigalpa",NOW(),0),
("Héctor Manuel", "Moncada Calix",NULL,7,7,"Tegucigalpa",NOW(),0),
("Delmy Suyapa", "Aguilar",NULL,5,5,"Tegucigalpa",NOW(),0),
("Cristian David", "Najera",NULL,12,12,"Tegucigalpa",NOW(),0)
